#version: 2026-02-25
#url=https://raw.githubusercontent.com/cracksecu/pihole/master/ads
static.media.net
media.net
adservetx.media.net
doubleclick.net/
ad.doubleclick.net/
static.doubleclick.net
m.doubleclick.net
mediavisor.doubleclick.net
media.fastclick.net/
analyticsengine.s3.amazonaws.com
affiliationjs.s3.amazonaws.com
advertising-api-eu.amazon.com
amazonclix.com
google-analytics.com
ssl.google-analytics.com
hotjar.com
static.hotjar.com
a.mouseflow.com
freshmarketer.com/
cdn.luckyorange.com
w1.luckyorange.com
stats.wp.com
api.bugsnag.com
app.bugsnag.com
browser.sentry-cdn.com
app.getsentry.com
advertising.twitter.com
analytics.pointdrive.linkedin.com
widgets.pinterest.com
d.reddit.com
samsungads.com
samsung-com.112.2o7.net
metrics.icloud.com
static.media.net
media.net
adservetx.media.net
doubleclick.net/
ad.doubleclick.net/
static.doubleclick.net
m.doubleclick.net
mediavisor.doubleclick.net
media.fastclick.net/
analyticsengine.s3.amazonaws.com
affiliationjs.s3.amazonaws.com
advertising-api-eu.amazon.com
amazonclix.com
google-analytics.com
ssl.google-analytics.com
hotjar.com
static.hotjar.com
a.mouseflow.com
freshmarketer.com/
cdn.luckyorange.com
w1.luckyorange.com
stats.wp.com
api.bugsnag.com
app.bugsnag.com
browser.sentry-cdn.com
app.getsentry.com
advertising.twitter.com
analytics.pointdrive.linkedin.com
widgets.pinterest.com
d.reddit.com
samsungads.com
samsung-com.112.2o7.net
metrics.icloud.com
amazonaax.com
amazonclix.com
freshmarketer.com
stats.wp.com
data.mistat.intl.xiaomi.com
data.mistat.india.xiaomi.com
data.mistat.rus.xiaomi.com
metrics5.data.hicloud.com 
